import wick from "wick";

import { TEXTEDITOR } from "./text";
import { SCALETL, SCALEBL, SCALETR, SCALEBR, SCALEL, SCALEB, SCALET, SCALER } from "./resize";
import { MOVE, CENTER } from "./move";
import { COMPLETE } from "./complete";
import { CREATE_COMPONENT, CREATE_CSS_DOC } from "./create";
import {
    TOMARGINLEFT,
    TOMARGINRIGHT,
    TOMARGINLEFTRIGHT,
    TOLEFT,
    TORIGHT,
    TOLEFTRIGHT,
    TOTOP,
    TOTOPBOTTOM,
    TOGGLE_UNIT,
    TOPOSITIONABSOLUTE,
    TOPOSITIONRELATIVE,
    TOPOSITIONFIXED,
    TOPOSITIONSTICKY,
} from "./convert";

const actions = {
    COMPLETE,
    TEXTEDITOR,
    MOVE,
    CENTER,
    SCALETL,
    SCALEBL,
    SCALETR,
    SCALEBR,
    SCALEL,
    SCALEB,
    SCALET,
    SCALER,
    CREATE_COMPONENT,
    CREATE_CSS_DOC,
    TOMARGINLEFT,
    TOMARGINRIGHT,
    TOMARGINLEFTRIGHT,
    TOLEFT,
    TORIGHT,
    TOLEFTRIGHT,
    TOTOP,
    TOTOPBOTTOM,
    TOGGLE_UNIT,
    TOPOSITIONABSOLUTE,
    TOPOSITIONRELATIVE,
    TOPOSITIONFIXED,
    TOPOSITIONSTICKY,
};

export { actions };